presubmits:
  - name: env-test-sample-prow-job
    decorate: true
    always_run: true
    spec:
      containers:
      - image: golang:1.20.2
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          env
